### ISSUE TITLE
Image large is none message?

### ISSUE THREAD

**Issue by PedroFabrino** [CodeWithMa/PVPokeLossBot#5]
Sorry, don't really know if I should post this here or where. Please correct me if anything.

I'm runnign the bot, got it connected to the phone, got detected and loaded the images, but this is what I get:

![image](https://github.com/CodeWithMa/PVPokeLossBot/assets/9949616/29f8d6f3-7b4f-4aef-9e40-8563bf733038)

I'm using Windows 11.

**Comment by CodeWithMa** [comment]
> Sorry, don't really know if I should post this here or where. Please correct me if anything.

This is the right place :)

> Image large is none

This message means, that the image capture was not successful. Can you check if the file `screenshot.png` which was created by the bot contains an actual image or is its file size 0 bytes?

The following command is run by the bot to capture the image. Can you run it and check the resulting image?

```shell
adb exec-out screencap -p > screenshot.png
```
