### ISSUE TITLE
Stuck 

### ISSUE THREAD

**Issue by IXeller** [CodeWithMa/PVPokeLossBot#6]
![image](https://github.com/CodeWithMa/PVPokeLossBot/assets/45758035/3523876a-fd4e-4c88-9257-d1eaa3d26d99)

Got Stuck on this Screen

Phone: Xiaomi 13T Pro

**Comment by IXeller** [comment]
Screenshots are taken

**Comment by CodeWithMa** [comment]
On which screen do you start the bot? You have to open the Battle Menu. Then start it. It should then detect the battle button.

This is an example screenshot from my device. 

![Start Screen](https://raw.githubusercontent.com/CodeWithMa/PVPokeLossBot/dev/tests/images/battle_button_1.png)

Maybe I have to adjust the thresholds for detecting if the screen resolutions differ.

**Comment by CodeWithMa** [comment]
Just added some more logging. You can try the newest version and run it with `--verbose`.

```shell
python main.py --verbose
```

It should output how much each image template matches the screenshot.
